spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clarity
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      #Set to create for initial table creation
      #ddl-auto: update
      ddl-auto: create